version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.devcontainer
    volumes:
      - ..:/workspace:delegated
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
      - serverless_forum_gems:/usr/local/bundle:delegated
      - serverless_forum_extensions:/root/.vscode-server:delegated
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: sleep infinity
  db:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
volumes:
  serverless_forum_extensions:
  serverless_forum_gems:
